name: test
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.13.1
          - 17.x
        redis-version: [7]
        mosquitto-version: [2]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Redis v${{ matrix.redis-version }}
        uses: superchargejs/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Start Mosquitto v${{ matrix.mosquitto-version }}
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: ${{ matrix.mosquitto-version }}
          config: ${{ github.workspace }}/mosquitto.conf
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
